language: java

jdk:
  - openjdk17

before_install:
  - chmod +x gradlew

before_deploy:
  - cp system.properties $HOME/.heroku/

script:
  - ./gradlew build

deploy:
  provider: heroku
  api_key: $HEROKU_TOKEN
  app: "book-demo-store-my-app"